export default seederWhisks = [
  {
    ID: '4cb5c93e-df43-4571-bca7-2ff8ce3ffb82',
    Type: 'Whisk',
    title: 'Coffee Date in Mt. Pleasant',
    images: [
      'https://res.cloudinary.com/fittco/image/upload/v1557509574/cshp6bekdicl5v7wqlgq.jpg',
    ],
    city: 'Vancouver',
    neighborhood: 'Mt Pleasant',
    description:
      'Cute coffee crawl around the Mt. Pleasant neighbourhood, exploring what the best cafes in this area have to offer - from bagels, croissants and other pastries.',
    durationHours: 2,
    participants: 2,
    category: 'food',
    tags: ['Coffee'],
    cost: '$',
  },
  {
    ID: 'cb4e4321-7def-4d63-923a-719b1f4ba068',
    Type: 'Whisk',
    title: 'Best Bar Patios Date',
    images: [
      "https://encrypted-tbn0.gstatic.com/'images'?q=tbn:ANd9GcQQ14dH_K9fffbCAeQ2Q2GHGoKsqq-sRx7",
    ],
    city: 'Vancouver',
    neighborhood: 'East Van',
    description:
      'A brewery crawl around this hip neighbourhood to six cozy spots for a casual drink',
    durationHours: 2,
    participants: 2,
    category: 'food',
    tags: ['Beer', 'Breweries'],
    cost: '$$',
  },
  {
    ID: '173105dc-f900-4790-9b76-21a902d44a23',
    Type: 'Whisk',
    title: 'Learn to pour beer date',
    images: [
      'https://i.insider.com/5a71fc6d46a2889d018b45a5?width=1067&format=jpeg',
    ],
    city: 'Port Moody',
    description:
      'Learn to pour like a pro from a professional.  Spend an afternoon practicing and drinking all your pours in a hip local brewery.',
    durationHours: 2,
    participants: 2,
    category: 'food',
    tags: ['Beer', 'Learn'],
    cost: '$$',
  },
  {
    ID: '43190d21-9fb9-462d-97d1-79d73e15262e',
    Type: 'Whisk',
    title: 'Ice Fishing with a Local',
    images: [
      'https://a0.muscache.com/im/pictures/lombard/MtTemplate-1175279-media_library/original/64cc3249-c5b4-494d-beab-6ee2fbc8f062.png?im_w=480',
      'https://www.chilcotinholidays.com/wp-content/uploads/ice-fishing-newsletter.jpg',
    ],
    city: 'Whistler',
    description:
      'Head over to one of the stocked lakes in Whistler to catch Rainbow Trout with an experienced local guide. You will need ice cleats and proper winter clothing.',
    durationHours: 2,
    participants: 4,
    category: 'adventure',
    tags: ['Fishing', 'Winter', 'Group'],
    cost: '$$$',
  },
  {
    ID: '28b2fef0-0fcd-4c8a-97c1-d691fdfb838e',
    Type: 'Whisk',
    title: 'Night Bio-Luminescence Boat Tour',
    images: [
      'https://a0.muscache.com/im/pictures/lombard/MtTemplate-1955707-media_library/original/cef24138-d5b1-490f-8b34-e8cc71cf6043.jpeg?im_w=1440',
    ],
    city: 'Sechelt',
    description:
      'Experience otherworldly bio-luminescence in an ocean bay off the coast of Halfmoon Bay, British Columbia. Get ready for what becomes magical--the sparkling ocean plankton coming alive - bio-luminescence surrounds us.',
    durationHours: 2,
    participants: 4,
    category: 'adventure',
    tags: ['Boat', 'Group'],
    cost: '$$$',
  },
  {
    ID: '0b909f66-e67b-43a2-bedd-b012016a90a9',
    Type: 'Whisk',
    title: 'Seafood Food Trucks in Steveston',
    images: [
      'https://www.thespruceeats.com/thmb/hToYLa2CWDEZKNX4VROsCSE3K0M=/1500x1000/filters:fill(auto,1)/best-fish-and-chips-recipe-434856-Hero-5b61b89346e0fb00500f2141.jpg',
    ],
    city: 'Richmond',
    neighborhood: 'Steveston',
    description:
      'Visit local food trucks in historic Steveston.  You will be provided with exclusive vouchers to vendors to taste only their best and freshest catch.',
    durationHours: 2,
    participants: 2,
    category: 'food',
    tags: ['Seafood', 'Historic'],
    cost: '$$',
  },
  {
    ID: 'c1997d26-c0a2-42e7-9251-97c9f9a7d65b',
    Type: 'Whisk',
    title: 'Beaches & Islands Paddleboard Tour',
    images: [
      'https://a0.muscache.com/im/pictures/2b94dbb2-4648-4e3c-9b6f-c0a2e3a7e381.jpg?im_w=1440',
      'https://a0.muscache.com/im/pictures/c34926e9-fb13-4ad0-880d-f6736021ba98.jpg?im_w=1440',
      'https://a0.muscache.com/im/pictures/fede252b-1b7d-4df4-a615-10d3192ddc5c.jpg?im_w=1440',
    ],
    city: 'Vancouver',
    neighborhood: 'UBC',
    description:
      'Your adventure will begin at a local beach.  You will be whisked away to private beaches with an experienced instructor. Paddleboard and wetsuit rental included.',
    durationHours: 3,
    participants: 2,
    category: 'outdoors',
    tags: ['Summer', 'Activity', 'Water'],
    cost: '$$$',
  },
  {
    ID: 'c13eafca-0ac8-4b48-8279-ff49c9727be9',
    Type: 'Whisk',
    title: 'Hike the Chief',
    images: [
      'https://www.insidevancouver.ca/wp-content/uploads/2016/07/Discover-the-Outdoors-Squamish-Chief6-550x413.jpg',
    ],
    city: 'Squamish',
    description:
      "Why not prove that you are truly the outdoorsy person you claim to be? Get ready for some one on one time, plenty of sweat and gorgeous views atop one of the largest granite monolihs in North America. Who wouldn't bond over an experience like that?",
    durationHours: 6,
    participants: 2,
    category: 'outdoors',
    tags: ['Hike', 'Views'],
    cost: '$',
  },
  {
    ID: 'dc9b8582-8e06-445c-a980-ed2a643ab0ef',
    Type: 'Whisk',
    title: 'MiLB at the Nat Bailey',
    images: [
      'https://smartcdn.prod.postmedia.digital/vancouversun/wp-content/uploads/2020/03/png0816n-canadians-baseball-2.jpg',
    ],
    city: 'Vancouver',
    neighborhood: 'Kensington',
    description:
      'Treat you and your date to an exciting game of baseball at the historic Nat Bailey stadium.',
    durationHours: 2,
    participants: 2,
    category: 'outdoors',
    tags: ['Sports'],
    cost: '$',
  },
  {
    ID: '8587804e-2fbb-43e1-8e54-aca1fb31b48e',
    Type: 'Whisk',
    title: 'Cats + Coffee at the Catfe',
    images: [
      'https://images.squarespace-cdn.com/content/v1/555050d2e4b06f76bea1ba86/1530063161393-J8JUBE8BZVPN5A8EDUWU/ke17ZwdGBToddI8pDm48kC2Ou1MO9kamcKms_rlnXOx7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0pTKqSDRwmMK43IUI3HojJWvxET3ZsoHLF25q9M0jMXigr6IB5A8OQ1JN_TuoaZPoQ/catfecover.jpg?format=1500w',
    ],
    city: 'Vancouver',
    neighborhood: 'Downtown',
    description: 'Play with furry felines and enjoy a delcious beverage',
    durationHours: 1,
    participants: 2,
    category: 'adventure',
    tags: ['Animals'],
    cost: '$',
  },
  {
    ID: '9df7d21f-f0c4-4283-ae87-60bafb16c629',
    Type: 'Whisk',
    title: 'Boardgames and Pizza',
    images: [
      'https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_450,q_50,w_600/https://assets.simpleviewinc.com/simpleview/image/upload/crm/vancouverbc/75561426_2395775444016434_4002768657829593088_o0-292077e45056b3a_2920790d-5056-b3a8-49601af87bcf3317.jpg',
    ],
    city: 'Vancouver',
    neighborhood: 'Mt Pleasant',
    description:
      'Board & card games entertain patrons at this lively pub with a sci-fi theme, bar fare & patio seats.',
    durationHours: 2,
    participants: 2,
    category: 'adventure',
    tags: ['Board Games'],
    cost: '$$',
  },
];
